global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'parking-system'
    static_configs:
      - targets: ['api:9090']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__scheme__]
        target_label: scheme
    metric_relabel_configs:
      - source_labels: [endpoint]
        regex: '/api/v1/.*'
        target_label: api_endpoint
        replacement: '${1}'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http'